NumPy

In [1]:
import numpy as np

numpy array 

In [3]:
arr = np.array([1,2,3,4,5,6,])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


tuple in numpy

In [5]:
arr = np.array((1,2,3,4,5,6,))
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


Dimension in array

In [7]:
#0D array
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


In [9]:
#1D array
arr = np.array([20,21,23])
print(arr)
print(type(arr))
print(arr.ndim)

[20 21 23]
<class 'numpy.ndarray'>
1


In [11]:
#2D array
arr1 = np.array([[20,21,23],[2,2,3]])
print(arr1)
print(type(arr1))
print(arr1.ndim)

[[20 21 23]
 [ 2  2  3]]
<class 'numpy.ndarray'>
2


In [15]:
#3D array
arr1 = np.array([[[20,21,23],[2,2,3],[30,31,32]]])
print(arr1)
print(type(arr1))
print(arr1.ndim)

[[[20 21 23]
  [ 2  2  3]
  [30 31 32]]]
<class 'numpy.ndarray'>
3


NUMPY ARRAY INDEX

In [22]:
arr = np.array([[21,23,34],
                [30,45,22]])
print(arr[0,0])
print(arr[1,1])
print(arr[1,2])

21
45
22


DAY 13:NUMPY CONTINUE 

Slicing  in array

In [35]:
ARR = np.array([[21,22,23,24,24,25],[31,32,33,34,35,36]])
print(ARR[0,1:4])
print(ARR[1,1:3])

[22 23 24]
[32 33]


3D array slicing

In [26]:
ARR = np.array([[[21,22,23,24,24,25],[31,32,33,34,35,36],[41,42,43,44,45,46]]])
print(ARR)

[[[21 22 23 24 24 25]
  [31 32 33 34 35 36]
  [41 42 43 44 45 46]]]


In [34]:
print("slicing in 3d array part1")
print(ARR[0,0,1:4])
print("slicing in 3d array part2")
print(ARR[0,1:3,1:4])


slicing in 3d array part1
[22 23 24]
slicing in 3d array part2
[[32 33 34]
 [42 43 44]]


Checking Data type of an Array

In [37]:
ARR = np.array([[[21,22,23,24,24,25],[31,32,33,34,35,36],[41,42,43,44,45,46]]])
print(type(ARR))
print(ARR.dtype)

<class 'numpy.ndarray'>
int32


In [38]:
ARR =np.array(["A","B","C"])
print(type(ARR))
print(ARR.dtype)

<class 'numpy.ndarray'>
<U1


CREATING ARRAY WITH DEFINED DATA TYPE

In [43]:
arr = np.array([21,23,34],dtype='S')
print(arr)
print(arr.dtype)

[b'21' b'23' b'34']
|S2


CREATING ARRAY WITH DATA TYPE 4 bytes integers

In [49]:
arr4 =np.array([1,2,3,4,5,6],dtype='i4') 
arr2 =np.array([1,2,3,4,5,6],dtype='i2')
arr8 =np.array([1,2,3,4,5,6],dtype='i8')
print(arr4)
print(arr4.dtype)
print(arr2.dtype)
print(arr8.dtype)


[1 2 3 4 5 6]
int32
int16
int64


NUMPY ARRAY SHAPE 

In [58]:
#shape of an array is number of elements in each direction

arr = np.array([[11,12,13,14,15,16],[21,22,23,24,25,26]])
print(arr)
print("shape of an above array is ",arr.shape)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]]
shape of an above array is  (2, 6)


In [59]:
arr = np.array([[[11,12,13,14,15,16],[21,22,23,24,25,26],[31,32,33,34,35,36]]])
print(arr)
print("shape of an above array is ",arr.shape)

[[[11 12 13 14 15 16]
  [21 22 23 24 25 26]
  [31 32 33 34 35 36]]]
shape of an above array is  (1, 3, 6)


In [63]:
arr = np.array([[[11,12,13,14,15,16],[21,22,23,24,25,26],[31,32,33,34,35,36]],[[11,12,13,14,15,16],[21,52,53,54,25,26],[31,32,33,34,35,36]],[[11,12,13,14,15,16],[21,22,23,24,25,26],[31,32,33,34,35,36]]])
print(arr)
print("shape of an above array is ",arr.shape)
print("different selected values are",arr[1,1,1:4])

[[[11 12 13 14 15 16]
  [21 22 23 24 25 26]
  [31 32 33 34 35 36]]

 [[11 12 13 14 15 16]
  [21 52 53 54 25 26]
  [31 32 33 34 35 36]]

 [[11 12 13 14 15 16]
  [21 22 23 24 25 26]
  [31 32 33 34 35 36]]]
shape of an above array is  (3, 3, 6)
different selected values are [52 53 54]


JOINING TWO NUMPY ARRAY

In [71]:
arr1= np.array([11,12,13,14])
arr2= np.array([21,22,23,24])
print("given arrays are  \n",arr1,"\n" , arr2)
print("arrays after joining")
arr3=np.concatenate((arr1,arr2))
print(arr3)


given arrays are  
 [11 12 13 14] 
 [21 22 23 24]
arrays after joining
[11 12 13 14 21 22 23 24]


JOINING 2D ARRAY

In [81]:
arr1= np.array([[11,12,13,14],[31,32,33,34]])
arr2= np.array([[21,22,23,24],[41,42,43,44]])
print("given arr1 are  \n\n",arr1)
print("given arr2 are  \n\n",arr2)
print("\n arrays after joining")
arr3=np.concatenate((arr1,arr2),axis=1)
arr4=np.concatenate((arr1,arr2),axis=0)
print(arr3)
print(arr4)

given arr1 are  

 [[11 12 13 14]
 [31 32 33 34]]
given arr2 are  

 [[21 22 23 24]
 [41 42 43 44]]

 arrays after joining
[[11 12 13 14 21 22 23 24]
 [31 32 33 34 41 42 43 44]]
[[11 12 13 14]
 [31 32 33 34]
 [21 22 23 24]
 [41 42 43 44]]


Spliting of an array

In [85]:
arr= np.array([11,12,13,14,15,16,17])
sarr =np.array_split(arr,2)
sarr4 =np.array_split(arr,4)
print("slipting given array into 2 parts\n",sarr)
print("slipting given array into 4 parts\n",sarr4)


slipting given array into 2 parts
 [array([11, 12, 13, 14]), array([15, 16, 17])]
slipting given array into 4 parts
 [array([11, 12]), array([13, 14]), array([15, 16]), array([17])]


RAVEL AND FLATTEN

In [91]:
#ITS CONVERT MULTI DIMENSION ARRAY INTO 1D ARRAU
arr1= np.array([[[11,12,13],[21,22,23],[31,32,33]]])
print(arr1)
print(arr1.ndim)
n=arr1.ravel()
k=arr1.flatten()
print(n)
print(k)

[[[11 12 13]
  [21 22 23]
  [31 32 33]]]
3
[11 12 13 21 22 23 31 32 33]
[11 12 13 21 22 23 31 32 33]


UNIQUE FUNCTION


In [92]:
U=np.array([1,2,3,3,4,5,5,6,7,8,9,64,4])
print(U)
N=np.unique(U)
print(N)

[ 1  2  3  3  4  5  5  6  7  8  9 64  4]
[ 1  2  3  4  5  6  7  8  9 64]


In [96]:
U=np.array([1,1,1,1,2,3,3,4,5,5,6,7,8,9,64,4])
print(U)
N=np.unique(U,return_index=True )
M=np.unique(U,return_counts=True )
print(N)
print(M)

[ 1  1  1  1  2  3  3  4  5  5  6  7  8  9 64  4]
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 64]), array([ 0,  4,  5,  7,  8, 10, 11, 12, 13, 14], dtype=int64))
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 64]), array([4, 1, 2, 2, 2, 1, 1, 1, 1, 1], dtype=int64))


DELETE

In [102]:
d=np.array([1,1,1,1,2,3,3,4,5,5,6,7,8,9,64,4])
d1=np.delete(d,[4])
print(d)
print(d1)

[ 1  1  1  1  2  3  3  4  5  5  6  7  8  9 64  4]
[ 1  1  1  1  3  3  4  5  5  6  7  8  9 64  4]


In [116]:
d=np.array([[1,2,3,4,5],[11,22,33,44,55],[1,2,3,4,5]])
d1=np.delete(d,1,axis=0)
d2=np.delete(d,1,axis=1)
print(d)
print("\n\n after delete \n",d1)
print("\n\n after delete \n",d2)

[[ 1  2  3  4  5]
 [11 22 33 44 55]
 [ 1  2  3  4  5]]


 after delete 
 [[1 2 3 4 5]
 [1 2 3 4 5]]


 after delete 
 [[ 1  3  4  5]
 [11 33 44 55]
 [ 1  3  4  5]]
